version: '3.8'

services:
  bot:
    # Build the Docker image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    container_name: derp_bot
    # Mount the .env file into the container for secret management
    # Make sure a .env file exists in the project root
    env_file:
      - .env
    # Automatically restart the container if it crashes or the system reboots
    restart: always
    # Optional: Mount the source code for development (comment out for production)
    # volumes:
    #   - ./derp:/app/derp
    # Optional: Set logging driver and options
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

# Optional: Define networks if needed
# networks:
#   default:
#     driver: bridge

# Optional: Define volumes if needed for persistent data
# volumes:
#   data: 