version: '3.8'

services:
  bot:
    # Build the Docker image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
      # Use BuildKit for better caching and features
      cache_from:
        - ghcr.io/astral-sh/uv:python3.13-bookworm
    container_name: derp_bot
    # Mount the .env file into the container for secret management
    # Make sure a .env file exists in the project root
    env_file:
      - .env
    # Security: run as non-root, read-only filesystem where possible
    user: "1000:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    # Automatically restart the container if it crashes or the system reboots
    restart: unless-stopped
